;;; im-ef-acme-theme.el --- Legible light theme with Acme/Plan 9 colors -*- lexical-binding:t -*-

;; Copyright (C) 2026 Isa Mert Gurbuz

;; Author: Generated
;; Maintainer: Generated
;; Keywords: faces, theme, accessibility

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:
;;
;; A light theme combining the ef-themes framework with the classic
;; Acme/Plan 9 color palette for a warm, paper-like appearance.

;; AI generated by combining the acme-theme with ef themes.

;;; Code:

(require 'ef-themes)

(defconst im-ef-acme-palette-partial
  '((cursor "#1054AF")
    (bg-main "#FFFFE8")
    (bg-dim "#EFEFD8")
    (bg-alt "#E5E5D0")
    (fg-main "#444444")
    (fg-dim "#988D6D")
    (fg-alt "#555599")
    (bg-active "#CCCCB7")
    (bg-inactive "#F8FCE8")
    (border "#B8B09A")

    ;; Core colors derived from Acme palette
    (red "#880000")
    (red-warmer "#aa0000")
    (red-cooler "#771133")
    (red-faint "#994444")
    (green "#005500")
    (green-warmer "#006600")
    (green-cooler "#007777")
    (green-faint "#556655")
    (yellow "#888838")
    (yellow-warmer "#996622")
    (yellow-cooler "#887744")
    (yellow-faint "#8a8a5a")
    (blue "#1054AF")
    (blue-warmer "#3355cc")
    (blue-cooler "#0066cc")
    (blue-faint "#5566aa")
    (magenta "#555599")
    (magenta-warmer "#665588")
    (magenta-cooler "#6644aa")
    (magenta-faint "#776699")
    (cyan "#007777")
    (cyan-warmer "#336666")
    (cyan-cooler "#006688")
    (cyan-faint "#557777")

    ;; Intense backgrounds for search, etc.
    (bg-red-intense "#F8E8E8")
    (bg-green-intense "#E8FCE8")
    (bg-yellow-intense "#E8EB98")
    (bg-blue-intense "#E1FAFF")
    (bg-magenta-intense "#FFEAFF")
    (bg-cyan-intense "#A8EFEB")

    ;; Subtle backgrounds
    (bg-red-subtle "#F8E8E8")
    (bg-green-subtle "#E8FCE8")
    (bg-yellow-subtle "#F8FCE8")
    (bg-blue-subtle "#E1FAFF")
    (bg-magenta-subtle "#FFEAFF")
    (bg-cyan-subtle "#A8EFEB")

    ;; Diff backgrounds
    (bg-added "#E8FCE8")
    (bg-added-faint "#F0FDF0")
    (bg-added-refine "#D0F0D0")
    (fg-added "#005500")

    (bg-changed "#F8FCE8")
    (bg-changed-faint "#FFFDE8")
    (bg-changed-refine "#E8EB98")
    (fg-changed "#888838")

    (bg-removed "#F8E8E8")
    (bg-removed-faint "#FDF0F0")
    (bg-removed-refine "#F0D0D0")
    (fg-removed "#880000")

    ;; Mode line
    (bg-mode-line-active "#E1FAFF")
    (fg-mode-line-active "#444444")

    ;; Special backgrounds
    (bg-completion "#E1FAFF")
    (bg-hover "#A8EFEB")
    (bg-hover-secondary "#E8FCE8")
    (bg-hl-line "#EFEFD8")
    (bg-paren-match "#A8EFEB")
    (bg-err "#F8E8E8")
    (bg-warning "#F8FCE8")
    (bg-info "#E8FCE8")
    (bg-region "#E8EB98")))

(defconst im-ef-acme-palette-mappings-partial
  '((err red)
    (warning yellow)
    (info green)

    (fg-link blue-cooler)
    (fg-link-visited magenta)
    (name blue)
    (keybind blue-warmer)
    (identifier magenta-faint)
    (fg-prompt blue)

    (builtin magenta)
    (comment green)
    (constant red)
    (fnname blue)
    (fnname-call blue-faint)
    (keyword blue)
    (preprocessor red)
    (docstring yellow)
    (string red)
    (type cyan-warmer)
    (variable blue-warmer)
    (variable-use blue-faint)
    (rx-backslash cyan-cooler)
    (rx-construct red)

    (accent-0 blue)
    (accent-1 red)
    (accent-2 green)
    (accent-3 magenta)

    (date-common cyan)
    (date-deadline red)
    (date-deadline-subtle red-faint)
    (date-event fg-alt)
    (date-holiday magenta)
    (date-now fg-main)
    (date-range fg-alt)
    (date-scheduled yellow)
    (date-scheduled-subtle yellow-faint)
    (date-weekday cyan)
    (date-weekend red-faint)

    (fg-prose-code red)
    (prose-done green)
    (fg-prose-macro cyan)
    (prose-metadata fg-dim)
    (prose-metadata-value fg-alt)
    (prose-table fg-alt)
    (prose-table-formula info)
    (prose-tag yellow-faint)
    (prose-todo red)
    (fg-prose-verbatim magenta)

    (mail-cite-0 blue)
    (mail-cite-1 magenta)
    (mail-cite-2 green)
    (mail-cite-3 cyan)
    (mail-part magenta-faint)
    (mail-recipient blue)
    (mail-subject red)
    (mail-other cyan)

    (bg-search-static bg-yellow-intense)
    (bg-search-current bg-cyan-intense)
    (bg-search-lazy bg-blue-intense)
    (bg-search-replace bg-red-intense)

    (bg-search-rx-group-0 bg-magenta-intense)
    (bg-search-rx-group-1 bg-green-intense)
    (bg-search-rx-group-2 bg-red-subtle)
    (bg-search-rx-group-3 bg-cyan-subtle)

    (rainbow-0 blue)
    (rainbow-1 red)
    (rainbow-2 green)
    (rainbow-3 magenta)
    (rainbow-4 cyan)
    (rainbow-5 yellow)
    (rainbow-6 blue-warmer)
    (rainbow-7 red-cooler)
    (rainbow-8 green-cooler)))

(defcustom im-ef-acme-palette-overrides nil
  "Overrides for `im-ef-acme-palette'."
  :group 'ef-themes
  :package-version '(ef-themes . "1.0.0")
  :type '(repeat (list symbol (choice symbol string)))
  :link '(info-link "(ef-themes) Palette overrides"))

(defconst im-ef-acme-palette
  (modus-themes-generate-palette
   im-ef-acme-palette-partial
   nil
   nil
   (append im-ef-acme-palette-mappings-partial ef-themes-palette-common)))

(modus-themes-theme
 'im-ef-acme
 'ef-themes
 "Legible light theme with warm Acme/Plan 9 colors."
 'light
 'im-ef-acme-palette
 nil
 'im-ef-acme-palette-overrides
 'ef-themes-custom-faces)

(provide 'im-ef-acme-theme)
;;; im-ef-acme-theme.el ends here
