# Defined in /tmp/fish.LxBfYJ/fishtricks.fish @ line 2
function fishtricks
	echo "Bang bang: !!  -> replaces with last command"
    echo "           !\$ -> replaces with last commands arguments"
    echo ""
    echo "Functions: funcsave, funcremove, funced"

    echo ""
    echo ""

    echo "Apps:"
    echo "      Arch          -> pacin, pacrem, pacsearch, aurin, aursearch, ..."
    echo "      Box           -> boxdownload, boxupload"
    echo "      Translate     -> transen, transtr, trans en:tr word_here"
    echo "      IP            -> ipinfo, ipaddr"
    echo "      mpsyt         -> youtube from commandline"
    echo "      weather       -> display a nice weather report"
    echo ""
    echo ""
    echo "Tools:"
    echo "      xcopy         -> some_command | copy, copies output"
    echo "      xpaste        -> paste clipboard content"
    echo "      ccat          -> cat with syntax highlighting and line numbers"
    echo "      catmd         -> display markdown preview"
    echo "      fuckall       -> killall with SIGKILL"
    echo "      extract       -> extract archives automatically"
    echo "      mkcd          -> mkdir and cd into it"
    echo "      utf8          -> convert encoding of a turkish file to utf8"
    echo "      ack           -> grep like tool for programming"
    echo "      glances       -> htop alternative"
    echo ""
    echo ""
    echo "Developer Tools:"
    echo "      avrflash      -> flash device using avr"
    echo "      hsbuildandrun -> build&run stack project"
    echo ""
    echo ""
    echo "Cheat Sheets:"
    echo "      howdoi        -> search for easy programming stuff "
    echo "      tldr          -> short man pages"
    echo "      cheat         -> same as above"
    echo ""
    echo ""
    echo "Online:"
    echo "      uploadfile           -> upload to 0x0.st"
    echo "      shortenurl           -> shorten url with 0x0.st"
    echo "      webdownload          -> downloads the given url for offline usage"
    echo ""
    echo ""
    echo "Routines:"
    echo "      owncloudsync         -> sync owncloud from commandline"
    echo "      plasmashell-restart  -> does that"
    echo ""
    echo ""
    echo "Fun stuff:"
    echo "      cava         -> Music visualizer"
end
