#!/bin/sh

# Set 5 desktops for each connected screen
xrandr -q | grep " connected" | cut -d' ' -f1 | xargs -i bspc monitor {} --reset-desktops I II III IV V

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true
bspc config window_gap            $(xrdb-get-value wm.gaps)
bspc config border_width          $(xrdb-get-value wm.border)

bspc rule --add '*:float'   state=floating
bspc rule --add '*:padtop'  state=floating
bspc rule --add 'float'     state=floating
bspc rule --add 'padtop'    state=floating

bspc rule --add mpv         state=floating
bspc rule --add Sxiv        state=floating
bspc rule --add Zenity      state=floating
bspc rule --add feh         state=floating

bspc rule --add Screenkey   manage=off

# Start WM related stuff
pgrep compton || compton &
pgrep sxhkd || sxhkd &
bar &
feh --bg-scale "$HOME/.config/wall.png"
