#!/bin/sh

. "$UTILS_FILE"

bspc monitor --reset-desktops I II III IV V

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true
bspc config window_gap            $(xrdb_get_value wm.gaps)
bspc config border_width          $(xrdb_get_value wm.border)

bspc rule --add Screenkey manage=off
bspc rule --add float     state=floating
bspc rule --add mpv       state=floating
bspc rule --add pad_top   state=floating
bspc rule --add Sxiv      state=floating
bspc rule --add Zenity    state=floating
bspc rule --add feh       state=floating

pgrep compton || compton &
pgrep sxhkd || sxhkd &
bar &
