#!/bin/sh

# Save the image in clipboard to given file name.
# If first argument is `--display` or `-d`, instead
# of saving, it will show the image in the image viewer.

if [ "$1" = "--display" ] || [ "$1" = "-d" ]; then
    file=$(mktemp "XXXXX.png")
    if xclip -selection clipboard -t image/png -o > "$file"; then
        feh "$file"
    else
        notify-send "Error" "No images in clipboard"
    fi
else
    xclip -selection clipboard -t image/png -o > "$*"
fi
