#!/bin/sh

set -e
set -o pipefail

notify-send "Bluetooth Headphones" "Trying to connect bluetooth headphones..."
SUDO_ASKPASS="$HOME/.scripts/askpass" sudo rfkill unblock 0
sleep 1

TAB="$(printf '\t')"
bluetoothctl << EOF
power on
connect BC:${TAB}
quit
EOF

notify-send "Bluetooth Headphones" "Connection will be established in just a moment..."
