#!/bin/bash

declare -A WM_CLASSES
WM_CLASSES=(
  ["vivaldi"]="Vivaldi-stable"
  ["vivaldi-stable"]="Vivaldi-stable"
  ["emacs"]="Emacs"
  ["emacsclient"]="Emacs"
)

# This only gets the first part of the command:
#   focus-or-run emacsclient -c
# then EXEC will be emacsclient so that we can easly match from the map above.
EXEC=$1
CLASS=${WM_CLASSES["$EXEC"]}

if [[ -z $CLASS ]] || ! xdo activate -N "$CLASS"; then
    echo "Running."
    "$@"
else
    echo "Focused."
fi
