#!/bin/sh

# This script gets the requested password from a keepass file.
# It uses gnome-keyring to get password for kdbx file.
# $KEYRING_ID is the name of password field for your keepass database
# in gnome-keyring.
# Save your keepass database password to keyring like this:
# secret-tool store --label=KeePassDbPassword name keepass

# Usage:
# getpassword "/path/to/password/entry"       => prints entry's password from keepass db
# getpassword "/path/to/password/entry" -dump => prints both username and password
# getpassword --keepass                       => print KDBX_FILE's password

# To see your keepass db structre, use this:
# secret-tool lookup name keepass | keepassxc-cli ls /path/to/keepass/db/file

KEYRING_ID=keepass
KDBX_FILE="$HOME/Documents/sync/passwords.kdbx"
PASSWORD_PATH="$1"

if [[ "$1" == "--keepass" ]]; then
    secret-tool lookup name "$KEYRING_ID"
    exit
fi

info=$(secret-tool lookup name "$KEYRING_ID" | keepassxc-cli show "$KDBX_FILE" "$PASSWORD_PATH")
username=$(echo "$info" | grep -i "username: " | cut -d: -f2 | xargs)
password=$(echo "$info" | grep -i "password: " | cut -d: -f2 | xargs)

if [[ "$2" == "-dump" ]]; then
    echo "$username"
    echo "$password"
else
    echo "$password"
fi
