#!/bin/sh -

# This script simply starts a hotspot.
# It asks you for a hotspot name and a password.
# To end the hotspot, call `hotspot-kill`.


#inputs=$(zenity --forms --title="Create Hotspot" --text="Please fill the fields" \
#   --add-entry="Hotspot name" \
#   --add-password="Hotspot password")
#hotspot_name=$(echo $inputs | cut -f1 -d "|")
#hotspot_password=$(echo $inputs | cut -f2 -d "|")

hotspot_name=$(zenity --entry --title "Hotspot name" --text "Enter your hotspot name")
hotspot_password=$(zenity --password --title "Hotspot password") 

gsudo rfkill unblock 0
gsudo create_ap wlp4s0 enp5s0 $hotspot_name $hotspot_password &>/dev/null &disown
