#!/usr/bin/env bash

# This script is responsible for creating polybar instance and configuring
# monitors, desktops. You can run this file if you connect a new monitor and
# it will rearrange everything.

# Close all instances of polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Check if there are more than one monitors
# if so, set MONITOR_MAIN and MONITOR_SECONDARY accordingly
monitors="$(xrandr -q | grep -w "connected" | cut -d' ' -f1)"

export MONITOR_MAIN=""
export MONITOR_SECONDARY=""

# External monitor should be the main monitor, if exists
case "$monitors" in
    *HDMI1*) export MONITOR_MAIN="HDMI1" ;;
    *HDMI2*) export MONITOR_MAIN="HDMI2" ;;
    *HDMI-1*) export MONITOR_MAIN="HDMI-1" ;;
    *HDMI-2*) export MONITOR_MAIN="HDMI-2" ;;
    *DP1*) export MONITOR_MAIN="DP1" ;;
    *DP2*) export MONITOR_MAIN="DP2" ;;
    *VGA1*) export MONITOR_MAIN="VGA1" ;;
    *VGA2*) export MONITOR_MAIN="VGA2" ;;
esac

if [[ -z "$MONITOR_MAIN" ]]; then
    export MONITOR_MAIN=$(echo "$monitors" | cut -d' ' -f1)
fi

polybar main &

# Run secondary polybar, if there is a secondary monitor
MONITOR_SECONDARY=$(sed "/$MONITOR_MAIN/d" <<< $monitors)
[[ -n "$MONITOR_SECONDARY" ]]; polybar secondary &

# Set background
feh --bg-scale "$HOME/.config/wall.png"

# Create 5 desktops for each monitor
xrandr -q | grep -w "connected" | cut -d' ' -f1 | xargs -I {} bspc monitor "{}" --reset-desktops I II III IV V

