#!/bin/bash


FIREFOX_PID=$(pidof firefox | awk '{print $1}')
QUTEBROWSER_PID=$(pidof qutebrowser | awk '{print $1}')

[[ -n $FIREFOX_PID ]] && FIREFOX_PPID=$(ps -o ppid= "$FIREFOX_PID")
[[ -n $QUTEBROWSER_PID ]] && QUTEBROWSER_PPID=$(ps -o ppid= "$QUTEBROWSER_PID")

kill -STOP $FIREFOX_PPID
mediastuff all_pause

if [[ ! -d ~/.cache/i3lock/current/ ]] || [[ ~/.config/wall.png -nt ~/.cache/i3lock/current/wall.png ]]; then
    notify-send "Locking" "Updating lockscreen stuff... This may take some time."
    betterlockscreen -u ~/.config/wall.png
fi

betterlockscreen --text "I WANNA FUCKING KILL MYSELF" --lock blur

[[ -n $FIREFOX_PID ]] && kill -CONT "$FIREFOX_PPID"
[[ -n $QUTEBROWSER_PID ]] && kill -CONT "$QUTEBROWSER_PPID"
