#!/bin/sh
KEYRING_ID=keepass
KDBX_FILE="$HOME/Documents/sync/passwords.kdbx"
ENTRIES=$()
ENTRY=$(secret-tool lookup name $KEYRING_ID | keepassxc-cli locate $KDBX_FILE / | tail -n +2 | rofi -fuzzy -dmenu -i)
if [ ! -z "$ENTRY" ]
then
    getpassword "$ENTRY" | xclip -selection clipboard
fi

# Clear clipboard after 45 secs
secs=$((45))
while [ $secs -gt 0 ]; do
   echo -ne "$secs\033[0K\r"
   sleep 1
   : $((secs--))
done

echo "" | xclip -selection clipboard
