#!/bin/bash

API="https://servis.mgm.gov.tr/web/"
UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
headers=('-H' "Origin: https://mgm.gov.tr" '-H' "Host: mgm.gov.tr" '-H' "User-Agent: $UA")

parseEvent() {
    event=""
    case $1 in
        "A") event="Açık" ;;
        "AB") event="Az Bulutlu" ;;
        "PB") event="Parçalı Bulutlu" ;;
        "CB") event="Çok Bulutlu" ;;
        "HY") event="Hafif Yağmurlu" ;;
        "Y") event="Yağmurlu" ;;
        "KY") event="Kuvvetli Yağmurlu" ;;
        "KKY") event="Karla Karışık Yağmurlu" ;;
        "HKY") event="Hafif Kar Yağışlı" ;;
        "K") event="Kar Yağışlı" ;;
        "YKY") event="Yoğun Kar Yağışlı" ;;
        "HSY") event="Hafif Sağanak Yağışlı" ;;
        "SY") event="Sağanak Yağışlı" ;;
        "KSY") event="Kuvvetli Sağanak Yağışlı" ;;
        "MSY") event="Mevzi Sağanak Yağışlı" ;;
        "DY") event="Dolu" ;;
        "GSY") event="Gökgürültülü Sağanak Yağışlı" ;;
        "KGY") event="Kuvvetli Gökgürültülü Sağanak Yağışlı" ;;
        "SIS") event="Sisli" ;;
        "PUS") event="Puslu" ;;
        "DMN") event="Dumanlı" ;;
        "KF") event="Kum veya Toz Taşınımı" ;;
        "R") event="Rüzgarlı" ;;
        "GKR") event="Güneyli Kuvvetli Rüzgar" ;;
        "KKR") event="Kuzeyli Kuvvetli Rüzgar" ;;
        "SCK") event="Sıcak" ;;
        "SGK") event="Soğuk" ;;
        "HHY") event="Yağışlı" ;;
    esac
    echo "$event"
}

findMerkez() {
    curl -s "${headers[@]}" "${API}merkezler?il=$IL&ilce=$ILCE" | jq '.[0]'
}

get() {
    query=$(echo "$MERKEZ" | jq ".${3}")
    curl -s  "${headers[@]}" "${API}${1}?${2}=${query}" | jq '.[0]'
}


RAW="no"
if [ $1 = "--help" ] || [ $1 = "-h" ]; then
    echo "mgm IL ILCE"
    exit
elif [ $1 = "--raw" ] || [ $1 =  "-r" ]; then
    shift
    RAW=yes
fi

IL="$1"
ILCE="$2"
MERKEZ=$(findMerkez "$IL" "$ILCE")

#get "sondurumlar" "merkezid" "merkezId"
#get "tahminler/saatlik" "istno" "saatlikTahminIstNo"
#get "tahminler/gunluk" "istno" "gunlukTahminIstNo"


sondurum=$(get "sondurumlar" "merkezid" "merkezId")
if [ $RAW = "yes" ]; then
    echo "$sondurum"
else
    humidity=$(echo "$sondurum" | jq '.nem')
    temperature=$(echo "$sondurum" | jq '.sicaklik')
    rainChance=$(echo "$sondurum" | jq '.yagis00Now')
    event=$(parseEvent "$(echo "$sondurum" | jq -r '.hadiseKodu')")

    echo "SONDURUM"
    echo "========"
    echo "Hadise:           $event"
    echo "Sicaklik:         $temperature"
    echo "Nem:              $humidity"
    echo "Yagmur olasiligi: $rainChance"
fi

# TODO: add peak points
