#!/bin/bash

# Play youtube link using mpd.
# Usage: mpd-yt play [youtube_url|direct_music_link] [OPTIONAL: track_name] [OPTIONAL: album_name] [OPTIONAL: artist_name]

cmd="$1"
url="$2"
track="$3"
album="$4"
artist="$5"
port=6600

function send_mpd_command {
    mpd_command="$1"
    mpd_id="$2"
    mpd_args="$3"
    echo -e "$mpd_command $mpd_id $mpd_args\nclose" | nc localhost $port
}

if [[ $url = *"youtube.com/watch"* ]]; then
    info_all=$(youtube-dl -f 'bestaudio[ext=m4a]' -o "%(title)s ^ %(duration)s ^ %(artist)s ^ %(album)s ^ %(track)s" "$url" -g --get-filename)
    url=$(echo $info_all | cut -d" " -f1)
    info=$(echo $info_all | cut -d" " -f2-)
    echo $info_all

    video_name=$(echo $info | cut -d^ -f1 | xargs)
    [[ -z $artist ]] && artist=$(echo $info | cut -d^ -f3 | xargs)
    [[ -z $album ]] && album=$(echo $info | cut -d^ -f4 | xargs)
    [[ -z $track ]] && track=$(echo $info | cut -d^ -f5 | xargs)
    [[ $track == "NA" ]] && track=$video_name
fi

while read answer; do
    read id_answer
    id=$(echo $id_answer | cut -d: -f2 | xargs)
    send_mpd_command addtagid $id "title \"$track\""
    send_mpd_command addtagid $id "artist \"$artist\""
    send_mpd_command addtagid $id "album \"$album\""

    [[ $cmd="play" ]] && send_mpd_command playid $id
    exit
done < <(echo -e "addid $url\nclose" | nc localhost $port)
