#!/bin/sh

# This script is called from mpv and it downloads subtitle using `subdl`, then
# loads downloaded subtitle into mpv.

MPV_SOCKET=/tmp/mpvsocket
file_path=$1
language=$2

echo 'show-text "Downloading subtitle..."' | socat - $MPV_SOCKET
if subdl --lang="$language" "$file_path"; then
  echo 'show-text "Subtitle downloaded."' | socat - $MPV_SOCKET
  sub_file_path="${file_path%.*}.srt"
  echo "sub-add \"$sub_file_path\"" | socat - $MPV_SOCKET
else
  echo 'show-text "Error while downloading subtitle!"' | socat - $MPV_SOCKET
fi
