#!/bin/sh

# - Set SSH_PASSWORD variable if you want to auto-login.
# - Some commands have interactive versions, they are prefixed with i.
#   ex. cl = icl

PORT=2222
MOUNT_POINT="$HOME/Workspace/phone"

adb_forward() {
    adb devices | grep -i unauthorized && echo "Look at your phone and accept the connection request." && exit
    adb forward tcp:2222 tcp:2222
}

connection_addr() {
    # TODO: if adb devices is empty, connect trough wifi
    adb_forward
    printf "localhost"
}

run_command() {
    if command -v sshpass >/dev/null 2>&1 && [ -n "$SSH_PASSWORD" ]; then
        sshpass -p "$SSH_PASSWORD" ssh -p $PORT "$(connection_addr)" "$@"
    else
        ssh -p $PORT "$(connection_addr)" "$@"
    fi
}

contact_list_interactive() {
    field=$1
    search_str=$2
    cmd=$3

    output=$(run_command termux-contact-list | jq "map(select(.name | test(\"$search_str\"; \"i\")))")
    echo "$output" | jq '.[]'

    echo "=============="
    printf "Which one? (Indexes start from 0!)\n> "
    read nth
    echo "=============="

    export RESULT=$(echo "$output" | jq -j ".[$nth]$field")
}

case "$1" in
    mount|fs)
        mkdir -p "$MOUNT_POINT"
        sshfs -p $PORT u0_a100@"$(connection_addr)":/storage/emulated/0 "$MOUNT_POINT"
        ;;
    umount|ufs)
        fusermount -u  "$MOUNT_POINT" && rmdir "$MOUNT_POINT" ;;
    ssh)
        TERM=xterm run_command
        ;;
    run|exec)
        shift
        run_command "$@"
        ;;
    contact*search|cs|contact*list|cl)
        shift;
        run_command termux-contact-list | jq "map(select(.name | test(\"$1\"; \"i\")))"
        ;;
    icontact*search|ics|icontact*list|icl)
        shift;
        contact_list_interactive ".number" "$1"
        printf "$RESULT" | xclip -selection clipboard
        ;;
    sms*list|sl)
        shift;
        run_command termux-sms-list | jq "map(select(.sender | test(\"$1\"; \"i\")))"
        ;;
    sms*send|ss)
        shift;
        run_command termux-sms-send "$@"
        ;;
    isms*send|iss)
        shift;
        contact_list_interactive ".number" "$1"
        sms_file=$(mktemp)
        $EDITOR "$sms_file"

        run_command <<EOF
            sms=\$(mktemp)
            printf "$(cat "$sms_file")" > "\$sms"
            termux-sms-send -n "$RESULT" < "\$sms"
            rm "\$sms"
EOF
        rm "$sms_file"
        ;;
    speak)
        shift;
        run_command termux-tts-speak "$@"
        ;;
esac
