#!/bin/bash

# BAR_BORDER is the border size of top bar (in my case polybar.)
# BAR_HEIGHT is the height of top bar.
# WINDOW_BORDER is the border size of windows.
BAR_BORDER=$(xrdb-get-value "bar.border")
BAR_HEIGHT=$(xrdb-get-value "bar.height")
WINDOW_BORDER=$(xrdb-get-value "wm.border")

function calendar {
    local GEOMETRY="100x20-$((WINDOW_BORDER + BAR_BORDER))+$((BAR_HEIGHT+BAR_BORDER))"
    local WINDOW_TITLE="calendar-popup-window"

    if [[ $(wmctrl -l) != *$WINDOW_TITLE* ]]; then
        term --float --opaque -T $WINDOW_TITLE -g $GEOMETRY -e ikhal
    else
        wmctrl -c $WINDOW_TITLE && vdirsyncer sync calendar
    fi
}

function music {
    MUSIC=ncmpcpp

    local SCREEN_WIDTH=$(bspwmc focused_window_width)
    local Y=$((BAR_HEIGHT+BAR_BORDER*2))
    local GEOMETRY="110x20-$(((SCREEN_WIDTH - 822) / 2))+$Y"
    local WINDOW_TITLE="Music Popup"

    if [[ $(wmctrl -l) != *$WINDOW_TITLE* ]]; then
        term --float --opaque -T "$WINDOW_TITLE" -g $GEOMETRY -e $MUSIC 2> /dev/null &
        bspwmc center_floating --name "$WINDOW_TITLE"
    else
        wmctrl -c "$WINDOW_TITLE"
    fi
}

function htop {
    local GEOMETRY="80x9-$((2*WINDOW_BORDER))+$((BAR_HEIGHT+BAR_BORDER*2))"
    local WINDOW_TITLE="Task manager"

    if [[ $(wmctrl -l) != *$WINDOW_TITLE* ]]; then
        term --float --opaque -T "$WINDOW_TITLE" -g $GEOMETRY -e htop
    else
        wmctrl -c "$WINDOW_TITLE"
    fi
}

function translate-term {
    local GEOMETRY="100x15-$((WINDOW_BORDER + BAR_BORDER))+$((BAR_HEIGHT+BAR_BORDER))"
    local WINDOW_TITLE="Translator (:set verbose 0/1)"
    local COMMAND="trans -sl en -hl tr -to tr -interactive -v -pager bat"

    if [[ $(wmctrl -l) != *$WINDOW_TITLE* ]]; then
        term --float --opaque -T "$WINDOW_TITLE" -g $GEOMETRY -e $COMMAND
    else
        wmctrl -c "$WINDOW_TITLE"
    fi
}

function translate-gui {
    qdbus io.crow_translate.CrowTranslate /io/crow_translate/CrowTranslate/MainWindow open
}

function translate {
    # Use crow-translate if its open
    if pgrep crow; then
        translate-gui
    else
        translate-term
    fi
}

function mail {
    local GEOMETRY="100x20-$((WINDOW_BORDER + BAR_BORDER))+$((BAR_HEIGHT+BAR_BORDER))"
    local WINDOW_TITLE="neomutt-popup-window"

    if [[ $(wmctrl -l) != *$WINDOW_TITLE* ]]; then
        term --float --opaque -T $WINDOW_TITLE -g $GEOMETRY -e neomutt
    else
        wmctrl -c $WINDOW_TITLE
    fi
}

case "$1" in
    "calendar")   calendar;;
    "mail")       mail;;
    "music")      music;;
    "htop")       htop;;
    "translate")  shift; translate "$@";;
esac
