#!/bin/bash

# This script opens $CALENDAR app in right-upper corner in the screen without
# violating the area of top bar. If the $CALENDAR is already open, it just
# closes it.

# Change $CALENDAR in ~/.profile if you want. Also it's assumed that the
# $CALENDAR is a cli app.

BAR_BORDER=$(xrdb-get-value "bar.border")
BAR_HEIGHT=$(xrdb-get-value "bar.height")
WINDOW_BORDER=$(xrdb-get-value "wm.border")
GEOMETRY="80x20-$((WINDOW_BORDER + BAR_BORDER))+$((BAR_HEIGHT+BAR_BORDER))"
WINDOW_TITLE="calendar-popup-window"

if [[ $(wmctrl -l) != *$WINDOW_TITLE* ]]; then
    $TERMINAL -A 255 -c "float" -T $WINDOW_TITLE -g $GEOMETRY -e $CALENDAR
else
    wmctrl -c $WINDOW_TITLE
fi
