#!/bin/bash

set -e
set -o pipefail

for arg; do
    case "$arg" in
        "--enable-nvidia") ENABLE_NVIDIA=1 ;;
        "--enable-urxvt")  ENABLE_URXVT=1  ;;
    esac
done

# install programs {{{
sudo pacman -S --noconfirm aria2c
sudo pacman -S --noconfirm bspwm sxhkd compton polybar
sudo pacman -S --noconfirm fish neovim
sudo pacman -S --noconfirm neomutt isync
sudo pacman -S --noconfirm khal todoman vdirsyncer
sudo pacman -S --noconfirm mpv mpd mpc ncmpcpp subdl
sudo pacman -S --noconfirm firefox qutebrowser
sudo pacman -S --noconfirm sxiv feh
sudo pacman -S --noconfirm ipython

sudo pacman -S ranger
trizen -S --noconfirm python-ueberzug-git

sudo pacman -S rofi
trizen -S --noconfirm rofi-calc

if [[ -n "$ENABLE_URXVT" ]]; then
    echo "→ urxvt is enabled."
    sudo pacman -S --noconfirm rtv
    trizen -S --noconfirm rxvt-unicode-truecolor urxvt-perls urxvt-resize-font-git
else
    echo "× urxvt is *not* enabled."
fi

if [[ -n "$ENABLE_NVIDIA" ]]; then
    echo "→ NVidia is enabled."
    trizen --noconfirm -S optimus-manager
else
    echo "× NVidia is *not* enabled."
fi
# }}}

# {{{ mpv
# Install thumbnailer script
mkdir -p ~/.config/mpv/scripts
curl -fsSlL https://github.com/TheAMM/mpv_thumbnail_script/releases/download/0.4.2/mpv_thumbnail_script_client_osc.lua > ~/.config/mpv/scripts/mpv_thumbnail_script_client_osc.lua
curl -fsSlL https://github.com/TheAMM/mpv_thumbnail_script/releases/download/0.4.2/mpv_thumbnail_script_server.lua > ~/.config/mpv/scripts/mpv_thumbnail_script_server.lua
# }}}

# proton mail {{{
trizen -S --noconfirm hydroxide-git
# TODO: auth etc
#}}}

# mutt & mbsync {{{
# Create cache folders etc.
mkdir -p ~/.cache/mutt
for filename in ~/.config/mutt/accounts/*rc; do
    mkdir -p ~/.maildir/"$(basename "$filename" rc)"
    mkdir -p ~/.cache/mutt/"$(basename "$filename" rc)"
    mkdir -p ~/.cache/mutt/"$(basename "$filename" rc)"/bodies
done
# }}}

# install st {{{
echo "===== Installing st ====="
cd /tmp
git clone https://github.com/isamert/st.git
cd st
sudo make install
trizen --noonfirm -S ttf-symbola # To fix crashes on emojis
echo "===== Finished ====="
# }}}

# aria2c {{{
ARIA2_CACHE_FOLDER=$HOME/.cache/aria2
mkdir -p "$ARIA2_CACHE_FOLDER"
touch "$ARIA2_CACHE_FOLDER/session"
# }}}

# mpd {{{
MPD_FOLDER=$HOME/.config/mpd
mkdir -p "$MPD_FOLDER/playlists"
touch "$MPD_FOLDER/mpd.db"
touch "$MPD_FOLDER/mpd.log"
touch "$MPD_FOLDER/mpdstate"
# }}}

# bspwm {{{
curl https://raw.githubusercontent.com/Chrysostomus/bspwm-scripts/master/bin/euclid_mover > ~/.local/bin/euclid_mover
# }}}

# install tridactyl native messenger (:installnative) {{{
curl -fsSl https://raw.githubusercontent.com/tridactyl/tridactyl/master/native/install.sh | bash
# }}}

# android development config {{{
sudo pacman -S --noconfirm android-tools android-udev
sudo usermod -aG adbusers "$LOGNAME" # In other distros its `plugdev` group
# }}}

# pacman configuration {{{
sudo sed -i 's/^#Color$/Color/' /etc/pacman.conf
sudo sed -i 's/^#VerbosePkgLists$/VerbosePkgLists/' /etc/pacman.conf
# }}}

# systemd configuration {{{
sudo sed -i 's/^#DefaultTimeoutStopSec=\w*$/DefaultTimeoutStopSec=15s/' /etc/systemd/system.conf

systemctl --user enable aria2c.service
systemctl --user enable clipmenud.service
systemctl --user enable emacs.service
systemctl --user enable mpd.socket
systemctl --user enable mpdscribble.service
systemctl --user enable geoclue-agent.service
systemctl --user enable redshift.service
systemctl --user enable syncthing.service
systemctl --user enable udiskie.service
systemctl --user enable unclutter.service
# }}}

# vi: foldmethod=marker
