#!/bin/bash

# Disable touchpad
xinput --disable $(xinput list | grep Touchpad | cut -f2 | cut -f2 -d "=")

# Disable intel wifi
sudo ifconfig wlp4s0 down

# Disable hdd power save
sudo hdparm -B 255 /dev/sda

