#!/bin/bash

# Changes default sink to next one and moves all inputs to new default sink.

readarray -t sinks <<< "$(pactl list sinks short | cut -f1)"
readarray -t inputs <<< "$(pactl list sink-inputs short | cut -f1)"
current_sink=$(pactl list sinks short | grep "RUNNING" | head -c 1)

new_sink=${sinks[0]}
for sink in "${sinks[@]}"; do
    if (( sink > current_sink )); then
        new_sink="$sink"
        break
    fi
done

# Move every input to new sink
for input in "${inputs[@]}"; do
    pacmd move-sink-input "$input" "$new_sink"
done

# Make new sink the default
pactl set-default-sink $new_sink
