#!/bin/bash

set -e
set -o pipefail

CURRENT_DATE=$(date +%F::%R:%S)

mkpath() {
    SAVE_PATH="$DIR_SCREENSHOTS/$1-$CURRENT_DATE.png"
    echo "$SAVE_PATH" | xclip -selection clipboard
    echo "$SAVE_PATH"
}

case "$1" in
    "--full") maim "$(mkpath full)"; ;;
    "--area") maim -s "$(mkpath area)" ;;
    "--wait-full") maim -d 5 "$(mkpath full)" ;;
    "--wait-area") maim -s -d 5 "$(mkpath area)" ;;
    "--clip-full") maim --hidecursor | xclip -selection clipboard -t image/png ;;
    "--clip-area") maim --hidecursor -s | xclip -selection clipboard -t image/png ;;
    "--edit-area") maim --hidecursor -s > /tmp/sssss.png; pinta /tmp/sssss.png ;;
    "--shadow-window") maim -st 9999999 | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage "$(mkpath shadowed)" ;;
esac

notify-send "Screenshot" "Screenshot saved and path is copied to clipboard (if any)"
