#!/bin/sh

case "$1" in
    "--full") maim $HOME/Pictures/screenshots/full-$(date +%F::%R:%S).png ;;
    "--area") maim -s $HOME/Pictures/screenshots/area-$(date +%F::%R:%S).png ;;
    "--wait-full") maim -d 5 $HOME/Pictures/screenshots/full-$(date +%F::%R:%S).png ;;
    "--wait-area") maim -s -d 5 $HOME/Pictures/screenshots/area-$(date +%F::%R:%S).png ;;
    "--clip-full") maim | xclip -selection clipboard -t image/png ;;
    "--clip-area") maim -s | xclip -selection clipboard -t image/png ;;
    "--shadow-window") maim -st 9999999 | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage $HOME/Pictures/screenshots/window-shadowed-$(date +%F::%R:%S).png ;;
esac
