#!/bin/bash

get_response() {
    curl --location --get --silent "http://sozluk.gov.tr/gts" --data-urlencode "ara=$*"
}

if [ "$1" = "--raw" ] || [ "$1" = "-r" ]; then
    shift
    response=$(get_response "$*")
    echo "$response" | jq -C | less --RAW-CONTROL-CHARS --quit-if-one-screen
else
    response=$(get_response "$*")
    echo "$response" | jq -C '.[] | .anlamlarListe | map({tur: (try .ozelliklerListe[].tam_adi catch ""), anlam: .anlam, ornek: (try {cumle: .orneklerListe[].ornek, yazar: .orneklerListe[].yazar[].kisa_adi} catch "")})' | less --RAW-CONTROL-CHARS --quit-if-one-screen
fi

