#!/bin/bash

# When using st, it expects window class properties while urxvt expects
# window name properties for enabling floating windows. So
# Rule for urxvt:
# bspc rule --add '*:float'   state=floating
# Rule for st:
# bspc rule --add 'float'     state=floating

# st, urxvt, urxvtc, alacritty
RUNNER='alacritty'
FLOAT=''
OPAQUE=''
GEOMETRY=''
NAME=''
OPTS=()

for arg; do
    case "$arg" in
        "--term="*) RUNNER=${arg#*=}; shift ;;
        "--name="*) NAME=${arg#*=}; shift ;;
        "--geometry="*) GEOMETRY=${arg#*=}; shift ;;
        "--float") FLOAT='1'; shift ;;
        "--opaque") OPAQUE='1'; shift ;;
    esac
done

if [[ $RUNNER == 'urxvtc' ]]; then
    if ! pgrep urxvtd; then
        urxvtd & disown
        sleep 0.5
    fi
fi

if [[ -n "$FLOAT" ]]; then
    case "$RUNNER" in
        "st")        OPTS+=(-c float) ;;
        "urxvt"*)    OPTS+=(-name float) ;;
        "alacritty") OPTS+=(--class float) ;;
    esac
fi

if [[ -n "$NAME" ]]; then
    case "$RUNNER" in
        "st")        OPTS+=(-c "$NAME") ;;
        "urxvt"*)    OPTS+=(-name "$NAME") ;;
        "alacritty") OPTS+=(--class "$NAME") ;;
    esac
fi

if [[ -n "$OPAQUE" ]]; then
    case "$RUNNER" in
        "st")        OPTS+=(-A 1) ;;
        "urxvt"*)    OPTS+=(-bg "$(xrdb-get-value '*background')") ;;
        "alacritty") OPTS+=(--option background_opacity=1) ;;
    esac
fi

if [[ -n "$GEOMETRY" ]]; then
    case "$RUNNER" in
        "st"|"urxvt"*) OPTS+=(-g "$GEOMETRY") ;;
        "alacritty")
            W=$(echo "$GEOMETRY" | cut -dx -f1)
            H=$(echo "$GEOMETRY" | cut -dx -f2)
            OPTS+=(--dimensions $W $H)
            if echo $GEOMETRY | grep "+"; then
               X=$(echo "$GEOMETRY" | cut -dx -f2 | cut -d+ -f2)
               Y=$(echo "$GEOMETRY" | cut -dx -f2 | cut -d+ -f3)
               OPTS+=(--position $X $Y)
            fi
            ;;
    esac
fi

$RUNNER "${OPTS[@]}" "$@"
