#!/bin/bash

# When using st, it expects window class properties while urxvt expects
# window name properties for enabling floating windows. So
# Rule for urxvt:
# bspc rule --add '*:float'   state=floating
# Rule for st:
# bspc rule --add 'float'     state=floating

# st, urxvt, urxvtc, alacritty
RUNNER='alacritty'
FLOAT=''
OPAQUE=''
GEOMETRY=''
NAME=''
OPTS=()

for arg; do
    case "$arg" in
        "--term="*) RUNNER=${arg#*=}; shift ;;
        "--name="*) NAME=${arg#*=}; shift ;;
        "--geometry="*) GEOMETRY=${arg#*=}; shift ;;
        "--float") FLOAT='1'; shift ;;
        "--opaque") OPAQUE='1'; shift ;;
    esac
done

if [[ $RUNNER == 'urxvtc' ]]; then
    if ! pgrep urxvtd; then
        urxvtd & disown
        sleep 0.5
    fi
fi

if [[ -n "$FLOAT" ]]; then
    case "$RUNNER" in
        "st") OPTS+=(-c float) ;;
        "urxvt"*) OPTS+=(-name float) ;;
        "alacritty") OPTS+=(--class float) ;;
    esac
fi

if [[ -n "$NAME" ]]; then
    case "$RUNNER" in
        "st") OPTS+=(-c "$NAME") ;;
        "urxvt"*) OPTS+=(-name "$NAME") ;;
        "alacritty") OPTS+=(--title "$NAME") ;;
    esac
fi

if [[ -n "$OPAQUE" ]]; then
    case "$RUNNER" in
        "st") OPTS+=(-A 1) ;;
        "urxvt"*) OPTS+=(-bg "$(xrdb-get-value '*background')") ;;
        "alacritty")
            # FIXME: use this when available instead of this god-awful solution
            # https://github.com/alacritty/alacritty/issues/1258
            sed '/background_opacity/c\background_opacity: 1.0' ~/.config/alacritty.yml > /tmp/alacritty.yml;
            OPTS+=(--config-file /tmp/alacritty.yml) ;;
    esac
fi

if [[ -n "$GEOMETRY" ]]; then
    case "$RUNNER" in
        "st"|"urxvt"*) OPTS+=(-g "$GEOMETRY") ;;
        "alacritty") OPTS+=(--dimensions "$(echo "$GEOMETRY" | cut -dx -f1)" "$(echo "$GEOMETRY" | cut -dx -f2)") ;;
    esac
fi

$RUNNER "${OPTS[@]}" "$@"
