#!/bin/bash

# st, urxvt, urxvtc
RUNNER='urxvtc'
FLOAT=''
OPAQUE=''
NAME=''
OPTS=()

for arg; do
    case "$arg" in
        "--term="*) RUNNER=${arg#*=}; shift ;;
        "--name="*) NAME=${arg#*=}; shift ;;
        "--float") FLOAT='1'; shift ;;
        "--opaque") OPAQUE='1'; shift ;;
    esac
done


if [[ -n "$FLOAT" ]]; then
    case "$RUNNER" in
        "st") OPTS+=(-c float) ;;
        "urxvt"*) OPTS+=(-name float) ;;
    esac
fi

if [[ -n "$NAME" ]]; then
    case "$RUNNER" in
        "st") OPTS+=(-n "$NAME") ;;
        "urxvt"*) OPTS+=(-name "$NAME") ;;
    esac
fi

if [[ -n "$OPAQUE" ]]; then
    case "$RUNNER" in
        "st") OPTS+=(-A 1) ;;
        "urxvt"*) OPTS+=(-bg "$(xrdb-get-value '*background')") ;;
    esac
fi

$RUNNER "${OPTS[@]}" "$@"
