#!/bin/bash

# When a job that is called with tsp finishes, this script is called.
# Need to set $TS_ONFINISH variable to path of this script. (See ~/.profile)

job_id="$1"
err="$2"
out_file="$3"
cmd="$4"

remaining_job_count=$(tsp | tail -n +2 | grep -cvE '^[0-9]+ +finished')

if [[ "$err" = 0 ]]; then
    icon=terminal
    title="finished"
    duration=5
else
    icon=error
    title="failed"
    duration=10

    # Put cmd into clipboard
    echo "$cmd" | xclip -selection clipboard
fi

notify-send \
    -i "$icon" \
    -t $((duration*1000))\
    "[TSP] job $title (remaining: $remaining_job_count)" \
    "$cmd"

