#!/bin/sh -
USBROOT="/run/media/isa/backup/"
if [ -d "$USBROOT" ]; then
    echo "$USBROOT is found"
    echo "SYNC starting for Documents"
    echo "==========================="
    sudo rsync -avh /home/isa/Documents/ $USBROOT/documents/ --delete
    echo ""
    echo "SYNC starting for Pictures"
    echo "==========================="
    sudo rsync -avh /home/isa/Pictures/ $USBROOT/pictures/ --delete
fi
