#!/bin/sh

xrdb_set_value() {
    # Usage:
    # xrdb_set_value "st.alpha" 200

    # This will not override ~/.Xresources, it will just update xrdb for this
    # session.
    echo "$1: $2" | xrdb -merge
}

xrdb_get_value() {
    # Usage:
    # xrdb_get_value "entry.example"

    xrdb -query | grep "$1" | cut -d ":" -f 2 | xargs
}

xres_read_value() {
    # Usage:
    # xres_read_value "st.alpha"
    # This will return the default value defined in ~/.Xresources, not the value
    # from `xrdb -query` which could be changed by xrdb_set_value dynamically.

    grep -v "!"  "$HOME/.Xresources" | grep "$1" | cut -d ":" -f 2 | xargs
}

screen_width() {
    xrandr -q | grep "Screen 0" | cut -d,  -f2 | cut -d" " -f3
}

# FIXME: make posix
center_window() {
    wid=''

    # wait until the window shows up and set $wid
    if [ -n "$1" ]; then
        IFS='=' read -ra ARGS <<< "$1"
        wid=$(xdotool search --sync "${ARGS[0]}" "${ARGS[1]}")
    else
        sleep 0.2
        wid=$(xdotool getactivewindow)
    fi

    SCREEN_WIDTH=$(screen_width)
    WIDTH=$(xwininfo -id "$wid" | grep Width | cut -d: -f2 | xargs)
    X=$(((SCREEN_WIDTH - WIDTH) / 2))

    xdotool windowmove $wid $X y
}
