#!/bin/bash

wid=''

# wait until the window shows up and set $wid
if [ -n "$1" ]; then
    IFS='=' read -ra ARGS <<< "$1"
    wid=$(xdotool search --sync "${ARGS[0]}" "${ARGS[1]}")
else
    sleep 0.2
    wid=$(xdotool getactivewindow)
fi

SCREEN_WIDTH=$(wm-screen-width)
WIDTH=$(xwininfo -id "$wid" | grep Width | cut -d: -f2 | xargs)
X=$(((SCREEN_WIDTH - WIDTH) / 2))

xdotool windowmove $wid $X y
