#!/bin/sh

file="$1"
input="$*"

if [ -f "$file" ]; then
    xclip -selection clipboard -t "$(file -b --mime-type "$file")" -i "$file"
elif [ -z "$input" ]; then
    xclip -selection clipboard <&0
else
    printf "$input" | xclip -selection clipboard
fi
