#!/bin/bash

function qutecmd {
    echo "$*" >> "$QUTE_FIFO"
}

info="$(menu passwords -dump)"
username=$(sed -n "1p" <<< "$info")
password=$(sed -n "2p" <<< "$info")

qutecmd "fake-key $username"
qutecmd "fake-key <Tab>"
qutecmd "fake-key $password"
